library(us.geonames)
res <- gn_search_state(t, c("VA", "WV"))
View(res)
library(leaflet)
leaflet(data = res) %>% addTiles() %>% addCircleMarkers(lng = PRIM_LONG_DEC, lat = PRIM_LAT_DEC)
leaflet(data = res) %>% addTiles() %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC)
r2 <- filter(res, FEATURE_CLASS != "Populated Place")
leaflet(data = re2) %>% addTiles() %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC)
leaflet(data = r2) %>% addTiles() %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC)
r2 <- filter(res, COUNTY_NAME == "Smyth")
leaflet(data = r2) %>% addTiles() %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC)
View(r2)
leaflet(data = r2) %>% addTiles() %>% addMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
library(htmltools)
leaflet(data = r2) %>% addTiles() %>% addMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
r2 <- filter(res, COUNTY_NAME == "Smyth" & FEATURE_CLASS != "Populated Place")
leaflet(data = r2) %>% addTiles() %>% addMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
leaflet(data = r2) %>% addProviderTiles("OpenTopoMap") %>% addMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
leaflet(data = r2) %>% addProviderTiles("OpenTopoMap") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
library(rgdal)
pnts <- matrix(res$PRIM_LAT_DEC, res$PRIM_LONG_DEC)
pnts <- matrix(res$PRIM_LAT_DEC, res$PRIM_LONG_DEC, ncol=2)
pnts <- matrix(res$PRIM_LAT_DEC, res$PRIM_LONG_DEC, nrow = 165)
pnts <- matrix(res$PRIM_LAT_DEC, res$PRIM_LONG_DEC, nrow = 165, ncol=2)
mcp <- chull(pnts)
coords <- pnts[c(mcp, mcp[1]), ]
coords
plot(coords)
pnts <- matrix(r2$PRIM_LAT_DEC, r2$PRIM_LONG_DEC, nrow = 4, ncol=2)
mcp <- chull(pnts)
coords <- pnts[c(mcp, mcp[1]), ]
plot(coords)
View(coords)
sp_poly <- SpatialPolygons(list(Polygons(list(Polygon(coords)), ID=1)))
sp_poly_df <- SpatialPolygonsDataFrame(sp_poly, data=data.frame(ID=1))
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME)) > addPolygons(sp_poly_df)
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME)) > addPolygons(sp_poly)
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME)) %>% addPolygons(sp_poly_df)
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME)) %>% addPolygons(sp_poly)
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME))
leaflet(data = r2) %>% addProviderTiles("Stamen.TonerLite") %>% addCircleMarkers(~PRIM_LONG_DEC, ~PRIM_LAT_DEC, popup = ~htmlEscape(FEATURE_NAME), weight = 1)


